### ISSUE TITLE
Error message "ERROR: Could not install packages due to an OSError" during installation

### ISSUE THREAD

**Issue by yuenherny** [XpressAI/xircuits#126]
**What kind of bug is it?**
- [ ] Xircuits Core (Jupyterlab related features)
- [ ] Xircuits Canvas (Custom RD related features)
- [ ] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [x] Not Sure

**Describe the bug**
Got this error message: "ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-uninstall-xgzi6dgr\\send2trash.exe'
Consider using the `--user` option or check the permissions." when trying to install Xircuits using "pip install xircuits[full]"

Conda version: 4.10.3
Python version: 3.9.10

**To Reproduce**
1. Create Python environment with Conda.
2. Run command "pip install xircuits[full]
3. Wait for the installation to progress.

**Expected behavior**
Done installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/59016908/159949014-b3611548-87a7-477e-ae2c-165cb9239e08.png)

**Tested on?**

- [x] Windows 10
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

**Additional context**

**Comment by yuenherny** [comment]
Thanks so much for the reply. @MFA-X-AI 

The following worked for me on Miniconda Prompt:
`python -m venv venv
venv\Scripts\activate
pip install xircuits`

I bumped into this error when I want to call `jupyter lab` or `jupyter notebook`:
`import win32api
ImportError: DLL load failed while importing win32api: The specified procedure could not be found.`

Apparently pywin32=303 has this issue. I used pywin32=225 instead, as per this [SO thread](https://stackoverflow.com/questions/68226255/how-to-fix-dll-load-failed-while-importing-win32api-in-jupyter-notebook-after).

Then only it works.
![image](https://user-images.githubusercontent.com/59016908/160225166-6e15e5d0-a919-4aa9-9c5d-b4bd0b22d9dc.png)

May I ask, this extension only works on Jupyter Lab and not Notebook right?

**Comment by MFA-X-AI** [comment]
> Apparently pywin32=303 has this issue. I used pywin32=225 instead, as per this [SO thread](https://stackoverflow.com/questions/68226255/how-to-fix-dll-load-failed-while-importing-win32api-in-jupyter-notebook-after).

That's very interesting, thanks for documenting it. 

> May I ask, this extension only works on Jupyter Lab and not Notebook right?
Yep, Xircuits is a Jupyterlab based extension, it comes along with Jupyterlab goodies. That to say, you can open and use notebooks in Jupyterlab. We also have plans to create notebook components so that you can do things in notebooks and port them into the canvas.

**Comment by MFA-X-AI** [comment]
Although it should've been fixed since 1.3, I've finally gotten to test it out myself and can confirm xircuits is fully functional in an conda env now.
