### ISSUE TITLE
Duplicate a component with a "duplicate" option from the context menu

### ISSUE THREAD

**Issue by yusufraji** [XpressAI/xircuits#184]
**What kind of feature is it?**
- [ ] Xircuits Core (Jupyterlab related features)
- [x] Xircuits Canvas (Custom RD related features)
- [ ] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [ ] Not Sure

**Is your feature request related to a problem? Please describe.**

At the moment, if one plans to duplicate a component, on will have to:

1. `right-click` on the component, to reveal a context menu
2. select `copy` from the context menu
3. `right-click` anywhere on the canvas (for the second time), to reveal the context menu
4. then select the `paste` option from the context menu

**Describe the solution you'd like**

I propose adding a `duplicate` option right below the `paste` option in the context menu, as it will reduce the number of steps required to duplicate a component. With this addition, one wouldn't have to right-click a second time to paste the component. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MFA-X-AI** [comment]
Long overdue thanks for the suggestion. Since we can do a proper copy paste using keyboard shortcuts now, it should be much easier and faster to use. 😄
