### ISSUE TITLE
Add context menu with "delete the line" function.

### ISSUE THREAD

**Issue by xrandx** [XpressAI/xircuits#264]
**Xircuits Version**
```bash
Name: xircuits
Version: 1.8.3
Summary: A JupyterLab extension for rendering and editing xircuit files.
Home-page: https://github.com/XpressAI/xircuits
Author: Xpress AI
Author-email: eduardo@xpress.ai
License: Apache-2.0
Location: /cephfs/tanghongjian/work/miniconda3/envs/plat/lib/python3.8/site-packages
Requires: gitpython, ipykernel, jinja2, jupyter-core, jupyter-packaging, jupyter-server, jupyterlab, jupyterlab-server, notebook-shim, packaging, pygithub, requests, tornado, tqdm
Required-by:
```
**What kind of feature is it?**
- [ ] Xircuits Core (Jupyterlab related features)
- [x] Xircuits Canvas (Custom RD related features)
- [ ] Xircuits Component Library
- [ ] Documentation
- [ ] Testing Automation
- [ ] Not Sure

**Is your feature request related to a problem? Please describe.**

When I was editing nodes, I couldn't remove the lines related to the node. What I could do was only remove my node and create a node again, which is stupid. Because I will loss other lines related to the node.

**Describe the solution you'd like**

Add context menu with "delete the line" function.

**Additional context**

![image](https://github.com/XpressAI/xircuits/assets/20301879/fc16e0c4-9803-4aef-b8e4-3bb637348e64)

**Comment by mansouralawi** [comment]
Hi @xrandx 

Thank you for taking the time to provide your feedback.

To help you with this, you can actually select a line/lines by holding `Shift` and then `Left-Click` on the line, and press `Del` to delete it. I hope this helps streamline your editing process until we can provide a more intuitive solution.

We appreciate your suggestion to add a "delete the line" function to the context menu. This seems like a user-friendly enhancement, and we are pleased to inform you that we’ve added it to our feature wish list. We plan to implement this in the next development cycle.

**Comment by xrandx** [comment]
> 

Thank you for your quick help. I can't find the "delete line" function after searching on your documentation site via Google. So, I wrote this issue.
